<?php
	declare(strict_types=1);
	/** @var FilterTitleExtension $this */
?>
<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

	<div class="form-group">
		<label class="group-name" for="check_type"><?= _t('ext.filter_title.check_type'); ?></label>
		<div class="group-controls">
			<select name="check_type" id="check_type">
				<option value="0"<?= $this->getSystemConfigurationValue('check_type') != '1' ? ' selected="selected"' : '' ?>><?php echo _t('ext.filter_title.block'); ?></option>
				<option value="1"<?= $this->getSystemConfigurationValue('check_type') == '1' ? ' selected="selected"' : '' ?>><?php echo _t('ext.filter_title.free'); ?></option>
			</select>
			<span title="<?php echo _t('ext.filter_title.check_type_desc'); ?>"><svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM216 336h24V272H216c-13.3 0-24-10.7-24-24s10.7-24 24-24h48c13.3 0 24 10.7 24 24v88h8c13.3 0 24 10.7 24 24s-10.7 24-24 24H216c-13.3 0-24-10.7-24-24s10.7-24 24-24zm40-208a32 32 0 1 1 0 64 32 32 0 1 1 0-64z"/></svg></span>
		</div>
	</div>

	<div class="form-group">
		<label class="group-name" for="blacklist_title_keywords"><?php echo _t('ext.filter_title.keywords'); ?></label>
		<div class="group-controls">
			<textarea name="blacklist_title_keywords" id="blacklist_title_keywords"><?php echo $this->getBlackKeywords(); ?></textarea>
			<span title="<?php echo _t('ext.filter_title.keywords_desc'); ?>"><svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM216 336h24V272H216c-13.3 0-24-10.7-24-24s10.7-24 24-24h48c13.3 0 24 10.7 24 24v88h8c13.3 0 24 10.7 24 24s-10.7 24-24 24H216c-13.3 0-24-10.7-24-24s10.7-24 24-24zm40-208a32 32 0 1 1 0 64 32 32 0 1 1 0-64z"/></svg></span>
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>
